agent_name: my_first_aea
author: fetchai
version: 0.27.0
description: A simple agent to demo the echo skill.
license: Apache-2.0
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeib3kmhqz4qswa223lj3xkoejy26z6nm6uwv4ms6wkcsvu2jyxmfjy
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.21.0:bafybeih2fcqpfyh6yafz3uajzf7hl5rdhrs3fhsgq7byh7fjbgljib4udu
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeifukwkfigvviysebfb4qzagkf5ykfpyxb5vpszsrfodfgi36o2uw4
- fetchai/state_update:1.0.0:bafybeieafoi45lra4vkmbv4rkxf3sedoh5lmtlbze27hubmhe74cheq53u
- open_aea/signing:1.0.0:bafybeiei6h5suazzfta7n3uyq7bsz26zkmdiiylptu5i44p7s2wiygxt24
skills:
- fetchai/echo:0.19.0:bafybeifrm3isiz5bnjk7qzdknnig2mboaymrjxtytj5ipwbgbvthvgue2q
default_connection: fetchai/stub:0.21.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <3.0.0,>=2.0.0
