agent_name: gym_aea
author: fetchai
version: 0.25.0
description: The gym aea demos the interaction between a skill containing a RL agent
  and a gym connection.
license: Apache-2.0
aea_version: '>=2.0.0, <3.0.0'
fingerprint:
  README.md: bafybeiezqjvhn3izsyoongmzc7glpdv233rmzzs6gimpspzw3cwx7ebysy
fingerprint_ignore_patterns: []
connections:
- fetchai/gym:0.19.0:bafybeia7ctmc7hznda6rwvmsojks4rchcfx7bxz5ebxoscyfqfj35grff4
contracts: []
protocols:
- fetchai/default:1.0.0:bafybeifukwkfigvviysebfb4qzagkf5ykfpyxb5vpszsrfodfgi36o2uw4
- fetchai/gym:1.0.0:bafybeifpbheoux5ml74owozmttnybnni5bdfgwkp6b43hviozhcvlnqjku
- fetchai/state_update:1.0.0:bafybeieafoi45lra4vkmbv4rkxf3sedoh5lmtlbze27hubmhe74cheq53u
- open_aea/signing:1.0.0:bafybeiei6h5suazzfta7n3uyq7bsz26zkmdiiylptu5i44p7s2wiygxt24
skills:
- fetchai/gym:0.20.0:bafybeigeynot5awu4fm3xo55igjatshjhyet4v3cdjjf54p4vaokewpthm
default_connection: fetchai/gym:0.19.0
default_ledger: fetchai
required_ledgers:
- fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
default_routing: {}
connection_private_key_paths: {}
dependencies:
  open-aea-ledger-fetchai:
    version: <3.0.0,>=2.0.0
